application: chattest27
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
  
- url: /room/.*
  script: chat_room.py

- url: /_ah/channel/.*
  script: chat_room.py  

- url: /home.*
  script: chat_operator.py
  
- url: /.*
  script: chat_base.py
  

