application: helplinechattest
version: 1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
  
- url: /room.*
  script: chat_room.py
  secure: always

- url: /_ah/channel/.*
  script: chat_channel.py  
  secure: always

- url: /home.*
  script: chat_operator.py
  secure: always
  
- url: /.*
  script: chat_base.py
  secure: always
  

